package types

type HardwareAddress = uint16 // Hardware register located at 0xFF00 - 0xFF7F & 0xFFFF

const (
	P1    HardwareAddress = 0xFF00 // Joypad select/input
	SB    HardwareAddress = 0xFF01 // Serial transfer data
	SC    HardwareAddress = 0xFF02 // Controls the serial port
	DIV   HardwareAddress = 0xFF04 // Divider register (upper 8 bits of SYS_CLK)
	TIMA  HardwareAddress = 0xFF05 // Timer register
	TMA   HardwareAddress = 0xFF06 // Loaded into TIMA when TIMA overflows
	TAC   HardwareAddress = 0xFF07 // Controls the timer
	IF    HardwareAddress = 0xFF0F // IF is used to request interrupts
	NR10  HardwareAddress = 0xFF10 // Channel 1 Sweep
	NR11  HardwareAddress = 0xFF11 // Channel 1 length timer & duty cycle
	NR12  HardwareAddress = 0xFF12 // Channel 1 volume & envelope
	NR13  HardwareAddress = 0xFF13 // Channel 1 period low
	NR14  HardwareAddress = 0xFF14 // Channel 1 period high & control
	NR21  HardwareAddress = 0xFF16 // Channel 2 length timer & duty cycle
	NR22  HardwareAddress = 0xFF17 // Channel 2 volume & envelope
	NR23  HardwareAddress = 0xFF18 // Channel 2 period low
	NR24  HardwareAddress = 0xFF19 // Channel 2 period high & control
	NR30  HardwareAddress = 0xFF1A // Channel 3 DAC enable
	NR31  HardwareAddress = 0xFF1B // Channel 3 length timer
	NR32  HardwareAddress = 0xFF1C // Channel 3 output level
	NR33  HardwareAddress = 0xFF1D // Channel 3 period low
	NR34  HardwareAddress = 0xFF1E // Channel 3 period high & control
	NR41  HardwareAddress = 0xFF20 // Channel 4 length timer
	NR42  HardwareAddress = 0xFF21 // Channel 4 volume & envelope
	NR43  HardwareAddress = 0xFF22 // Channel 4 frequency & randomness
	NR44  HardwareAddress = 0xFF23 // Channel 4 control
	NR50  HardwareAddress = 0xFF24 // Master volume & VIN panning
	NR51  HardwareAddress = 0xFF25 // Sound panning
	NR52  HardwareAddress = 0xFF26 // Sound On/Off
	LCDC  HardwareAddress = 0xFF40 // LCDC is used to control the LCD
	STAT  HardwareAddress = 0xFF41 // Reports the LCD status
	SCY   HardwareAddress = 0xFF42 // Vertical scroll position of background
	SCX   HardwareAddress = 0xFF43 // Horizontal scroll position of the background
	LY    HardwareAddress = 0xFF44 // LY is the current scanline
	LYC   HardwareAddress = 0xFF45 // Compared to LY and sets the LYC coincidence flag
	DMA   HardwareAddress = 0xFF46 // DMA Source address & control
	BGP   HardwareAddress = 0xFF47 // Background palette data
	OBP0  HardwareAddress = 0xFF48 // Object palette 0 data
	OBP1  HardwareAddress = 0xFF49 // Object palette 1 data
	WY    HardwareAddress = 0xFF4A // Window Y position
	WX    HardwareAddress = 0xFF4B // Window X position + 7
	KEY0  HardwareAddress = 0xFF4C // Indicates CGB compatibility mode
	KEY1  HardwareAddress = 0xFF4D // Used for speed switching in CGB mode
	VBK   HardwareAddress = 0xFF4F // VRAM Bank (1-bit)
	BDIS  HardwareAddress = 0xFF50 // (B)oot ROM (d)(i)(s)able
	HDMA1 HardwareAddress = 0xFF51 // VRAM DMA source (high)
	HDMA2 HardwareAddress = 0xFF52 // VRAM DMA source (low)
	HDMA3 HardwareAddress = 0xFF53 // VRAM DMA destination (high)
	HDMA4 HardwareAddress = 0xFF54 // VRAM DMA destination (low)
	HDMA5 HardwareAddress = 0xFF55 // VRAM DMA length/mode/start
	BCPS  HardwareAddress = 0xFF68 // Background colour palette specification
	BCPD  HardwareAddress = 0xFF69 // Background colour palette data
	OCPS  HardwareAddress = 0xFF6A // Object colour palette specification
	OCPD  HardwareAddress = 0xFF6B // Object colour palette data
	OPRI  HardwareAddress = 0xFF6C // Sets sprite priority in CGB mode
	SVBK  HardwareAddress = 0xFF70 // WRAM Bank 01h-07h
	RP    HardwareAddress = 0xFF56 // Controls the IR port
	FF72  HardwareAddress = 0xFF72 // Undocumented
	FF73  HardwareAddress = 0xFF73 // Undocumented
	FF74  HardwareAddress = 0xFF74 // Undocumented
	FF75  HardwareAddress = 0xFF75 // Undocumented
	PCM12 HardwareAddress = 0xFF76 // Channel 1/2 PCM data
	PCM34 HardwareAddress = 0xFF77 // Channel 3/4 PCM Data
	IE    HardwareAddress = 0xFFFF // Controls which interrupts are enabled
)
