// Code generated by "stringer -type=EventType -output=event_string.go"; DO NOT EDIT.

package scheduler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[APUFrameSequencer-0]
	_ = x[APUFrameSequencer2-1]
	_ = x[APUChannel1-2]
	_ = x[APUChannel2-3]
	_ = x[APUChannel3-4]
	_ = x[APUSample-5]
	_ = x[EIPending-6]
	_ = x[EIHaltDelay-7]
	_ = x[PPUStartHBlank-8]
	_ = x[PPUHBlank-9]
	_ = x[PPUHBlankInterrupt-10]
	_ = x[PPUBeginFIFO-11]
	_ = x[PPUFIFOTransfer-12]
	_ = x[PPUEndFIFO-13]
	_ = x[PPUStartOAMSearch-14]
	_ = x[PPUEndFrame-15]
	_ = x[PPUContinueOAMSearch-16]
	_ = x[PPUPrepareEndOAMSearch-17]
	_ = x[PPUEndOAMSearch-18]
	_ = x[PPULine153Continue-19]
	_ = x[PPULine153End-20]
	_ = x[PPUStartVBlank-21]
	_ = x[PPUContinueVBlank-22]
	_ = x[PPUVRAMTransfer-23]
	_ = x[PPUStartGlitchedLine0-24]
	_ = x[PPUMiddleGlitchedLine0-25]
	_ = x[PPUContinueGlitchedLine0-26]
	_ = x[PPUEndGlitchedLine0-27]
	_ = x[PPUOAMInterrupt-28]
	_ = x[DMAStartTransfer-29]
	_ = x[DMAEndTransfer-30]
	_ = x[DMATransfer-31]
	_ = x[TimerTIMAReload-32]
	_ = x[TimerTIMAFinishReload-33]
	_ = x[TimerTIMAIncrement-34]
	_ = x[SerialBitTransfer-35]
	_ = x[SerialBitInterrupt-36]
	_ = x[CameraShoot-37]
}

const _EventType_name = "APUFrameSequencerAPUFrameSequencer2APUChannel1APUChannel2APUChannel3APUSampleEIPendingEIHaltDelayPPUStartHBlankPPUHBlankPPUHBlankInterruptPPUBeginFIFOPPUFIFOTransferPPUEndFIFOPPUStartOAMSearchPPUEndFramePPUContinueOAMSearchPPUPrepareEndOAMSearchPPUEndOAMSearchPPULine153ContinuePPULine153EndPPUStartVBlankPPUContinueVBlankPPUVRAMTransferPPUStartGlitchedLine0PPUMiddleGlitchedLine0PPUContinueGlitchedLine0PPUEndGlitchedLine0PPUOAMInterruptDMAStartTransferDMAEndTransferDMATransferTimerTIMAReloadTimerTIMAFinishReloadTimerTIMAIncrementSerialBitTransferSerialBitInterruptCameraShoot"

var _EventType_index = [...]uint16{0, 17, 35, 46, 57, 68, 77, 86, 97, 111, 120, 138, 150, 165, 175, 192, 203, 223, 245, 260, 278, 291, 305, 322, 337, 358, 380, 404, 423, 438, 454, 468, 479, 494, 515, 533, 550, 568, 579}

func (i EventType) String() string {
	if i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
