// Code generated by "stringer -type=EventType -output=event_string.go"; DO NOT EDIT.

package scheduler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[APUFrameSequencer-0]
	_ = x[APUFrameSequencer2-1]
	_ = x[APUChannel1-2]
	_ = x[APUChannel2-3]
	_ = x[APUChannel3-4]
	_ = x[APUSample-5]
	_ = x[EIPending-6]
	_ = x[EIHaltDelay-7]
	_ = x[PPUStartHBlank-8]
	_ = x[PPUHBlank-9]
	_ = x[PPUHBlankInterrupt-10]
	_ = x[PPUStartOAMSearch-11]
	_ = x[PPUEndFrame-12]
	_ = x[PPUContinueOAMSearch-13]
	_ = x[PPUPrepareEndOAMSearch-14]
	_ = x[PPUEndOAMSearch-15]
	_ = x[PPULine153Continue-16]
	_ = x[PPULine153End-17]
	_ = x[PPUStartVBlank-18]
	_ = x[PPUContinueVBlank-19]
	_ = x[PPUVRAMTransfer-20]
	_ = x[PPUStartGlitchedLine0-21]
	_ = x[PPUMiddleGlitchedLine0-22]
	_ = x[PPUContinueGlitchedLine0-23]
	_ = x[PPUEndGlitchedLine0-24]
	_ = x[PPUOAMInterrupt-25]
	_ = x[DMAStartTransfer-26]
	_ = x[DMAEndTransfer-27]
	_ = x[DMATransfer-28]
	_ = x[TimerTIMAReload-29]
	_ = x[TimerTIMAFinishReload-30]
	_ = x[TimerTIMAIncrement-31]
	_ = x[SerialBitTransfer-32]
	_ = x[SerialBitInterrupt-33]
	_ = x[CameraShoot-34]
}

const _EventType_name = "APUFrameSequencerAPUFrameSequencer2APUChannel1APUChannel2APUChannel3APUSampleEIPendingEIHaltDelayPPUStartHBlankPPUHBlankPPUHBlankInterruptPPUStartOAMSearchPPUEndFramePPUContinueOAMSearchPPUPrepareEndOAMSearchPPUEndOAMSearchPPULine153ContinuePPULine153EndPPUStartVBlankPPUContinueVBlankPPUVRAMTransferPPUStartGlitchedLine0PPUMiddleGlitchedLine0PPUContinueGlitchedLine0PPUEndGlitchedLine0PPUOAMInterruptDMAStartTransferDMAEndTransferDMATransferTimerTIMAReloadTimerTIMAFinishReloadTimerTIMAIncrementSerialBitTransferSerialBitInterruptCameraShoot"

var _EventType_index = [...]uint16{0, 17, 35, 46, 57, 68, 77, 86, 97, 111, 120, 138, 155, 166, 186, 208, 223, 241, 254, 268, 285, 300, 321, 343, 367, 386, 401, 417, 431, 442, 457, 478, 496, 513, 531, 542}

func (i EventType) String() string {
	if i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
