// Code generated by "stringer -type=LineState,OffscreenLineState,FetcherState -output=ppu_string.go"; DO NOT EDIT.

package ppu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StartOAMScanAfterTurnOn-0]
	_ = x[StartOAMScan-1]
	_ = x[ReleaseOAMBus-2]
	_ = x[AcquireOAMBus-3]
	_ = x[StartPixelTransfer-4]
	_ = x[PixelTransferDummy-5]
	_ = x[PixelTransferSCXDiscard-6]
	_ = x[PixelTransferLX0-7]
	_ = x[PixelTransferLX8-8]
	_ = x[EnterHBlank-9]
	_ = x[HBlankUpdateOAM-10]
	_ = x[HBlankUpdateLY-11]
	_ = x[HBlankUpdateLYCInt-12]
	_ = x[HBlankEnd-13]
	_ = x[HBlankLastLine-14]
	_ = x[HBlankLastLineLYCInt-15]
	_ = x[HBlankLastLineEnd-16]
}

const _LineState_name = "StartOAMScanAfterTurnOnStartOAMScanReleaseOAMBusAcquireOAMBusStartPixelTransferPixelTransferDummyPixelTransferSCXDiscardPixelTransferLX0PixelTransferLX8EnterHBlankHBlankUpdateOAMHBlankUpdateLYHBlankUpdateLYCIntHBlankEndHBlankLastLineHBlankLastLineLYCIntHBlankLastLineEnd"

var _LineState_index = [...]uint16{0, 23, 35, 48, 61, 79, 97, 120, 136, 152, 163, 178, 192, 210, 219, 233, 253, 270}

func (i LineState) String() string {
	if i < 0 || i >= LineState(len(_LineState_index)-1) {
		return "LineState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LineState_name[_LineState_index[i]:_LineState_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StartVBlank-0]
	_ = x[VBlankUpdateLY-1]
	_ = x[StartVBlankLastLine-2]
	_ = x[VBlankLastLine-3]
	_ = x[VBlankLastLineUpdateLYCInt-4]
	_ = x[VBlankLastLineUpdateHBlank-5]
	_ = x[VBlankEnd-6]
}

const _OffscreenLineState_name = "StartVBlankVBlankUpdateLYStartVBlankLastLineVBlankLastLineVBlankLastLineUpdateLYCIntVBlankLastLineUpdateHBlankVBlankEnd"

var _OffscreenLineState_index = [...]uint8{0, 11, 25, 44, 58, 84, 110, 119}

func (i OffscreenLineState) String() string {
	if i < 0 || i >= OffscreenLineState(len(_OffscreenLineState_index)-1) {
		return "OffscreenLineState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OffscreenLineState_name[_OffscreenLineState_index[i]:_OffscreenLineState_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BGWinActivating-0]
	_ = x[BGGetTileNoT1-1]
	_ = x[BGGetTileNoT2-2]
	_ = x[BGGetTileDataLowT1-3]
	_ = x[BGGetTileDataHighT2-4]
	_ = x[BGGetTileDataHighT1-5]
	_ = x[BGWinGetTileDataHighT2-6]
	_ = x[BGWinPushPixels-7]
	_ = x[WinActivating-8]
	_ = x[WinGetTileNoT1-9]
	_ = x[WinGetTileNoT2-10]
	_ = x[WinGetTileDataLowT1-11]
	_ = x[WinGetTileDataLowT2-12]
	_ = x[WinGetTileDataHighT1-13]
	_ = x[OBJGetTileNoT1-14]
	_ = x[OBJGetTileNoT2-15]
	_ = x[OBJGetTileDataLowT1-16]
	_ = x[OBJGetTileDataLowT2-17]
	_ = x[OBJGetTileDataHighT1-18]
	_ = x[OBJGetTileDataHighT2-19]
}

const _FetcherState_name = "BGWinActivatingBGGetTileNoT1BGGetTileNoT2BGGetTileDataLowT1BGGetTileDataHighT2BGGetTileDataHighT1BGWinGetTileDataHighT2BGWinPushPixelsWinActivatingWinGetTileNoT1WinGetTileNoT2WinGetTileDataLowT1WinGetTileDataLowT2WinGetTileDataHighT1OBJGetTileNoT1OBJGetTileNoT2OBJGetTileDataLowT1OBJGetTileDataLowT2OBJGetTileDataHighT1OBJGetTileDataHighT2"

var _FetcherState_index = [...]uint16{0, 15, 28, 41, 59, 78, 97, 119, 134, 147, 161, 175, 194, 213, 233, 247, 261, 280, 299, 319, 339}

func (i FetcherState) String() string {
	if i < 0 || i >= FetcherState(len(_FetcherState_index)-1) {
		return "FetcherState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FetcherState_name[_FetcherState_index[i]:_FetcherState_index[i+1]]
}
