// Code generated by "stringer -type=CartridgeType -output=cartridge_string.go"; DO NOT EDIT.

package io

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ROM-0]
	_ = x[MBC1-1]
	_ = x[MBC1RAM-2]
	_ = x[MBC1RAMBATT-3]
	_ = x[MBC2-5]
	_ = x[MBC2BATT-6]
	_ = x[ROMRAM-8]
	_ = x[ROMRAMBATT-9]
	_ = x[MMM01-11]
	_ = x[MMM01RAM-12]
	_ = x[MMM01RAMBATT-13]
	_ = x[MBC3TIMERBATT-15]
	_ = x[MBC3TIMERRAMBATT-16]
	_ = x[MBC3-17]
	_ = x[MBC3RAM-18]
	_ = x[MBC3RAMBATT-19]
	_ = x[MBC5-25]
	_ = x[MBC5RAM-26]
	_ = x[MBC5RAMBATT-27]
	_ = x[MBC5RUMBLE-28]
	_ = x[MBC5RUMBLERAM-29]
	_ = x[MBC5RUMBLERAMBATT-30]
	_ = x[POCKETCAMERA-252]
	_ = x[BANDAITAMA5-253]
	_ = x[HUDSONHUC3-254]
	_ = x[HUDSONHUC1-255]
}

const (
	_CartridgeType_name_0 = "ROMMBC1MBC1RAMMBC1RAMBATT"
	_CartridgeType_name_1 = "MBC2MBC2BATT"
	_CartridgeType_name_2 = "ROMRAMROMRAMBATT"
	_CartridgeType_name_3 = "MMM01MMM01RAMMMM01RAMBATT"
	_CartridgeType_name_4 = "MBC3TIMERBATTMBC3TIMERRAMBATTMBC3MBC3RAMMBC3RAMBATT"
	_CartridgeType_name_5 = "MBC5MBC5RAMMBC5RAMBATTMBC5RUMBLEMBC5RUMBLERAMMBC5RUMBLERAMBATT"
	_CartridgeType_name_6 = "POCKETCAMERABANDAITAMA5HUDSONHUC3HUDSONHUC1"
)

var (
	_CartridgeType_index_0 = [...]uint8{0, 3, 7, 14, 25}
	_CartridgeType_index_1 = [...]uint8{0, 4, 12}
	_CartridgeType_index_2 = [...]uint8{0, 6, 16}
	_CartridgeType_index_3 = [...]uint8{0, 5, 13, 25}
	_CartridgeType_index_4 = [...]uint8{0, 13, 29, 33, 40, 51}
	_CartridgeType_index_5 = [...]uint8{0, 4, 11, 22, 32, 45, 62}
	_CartridgeType_index_6 = [...]uint8{0, 12, 23, 33, 43}
)

func (i CartridgeType) String() string {
	switch {
	case i <= 3:
		return _CartridgeType_name_0[_CartridgeType_index_0[i]:_CartridgeType_index_0[i+1]]
	case 5 <= i && i <= 6:
		i -= 5
		return _CartridgeType_name_1[_CartridgeType_index_1[i]:_CartridgeType_index_1[i+1]]
	case 8 <= i && i <= 9:
		i -= 8
		return _CartridgeType_name_2[_CartridgeType_index_2[i]:_CartridgeType_index_2[i+1]]
	case 11 <= i && i <= 13:
		i -= 11
		return _CartridgeType_name_3[_CartridgeType_index_3[i]:_CartridgeType_index_3[i+1]]
	case 15 <= i && i <= 19:
		i -= 15
		return _CartridgeType_name_4[_CartridgeType_index_4[i]:_CartridgeType_index_4[i+1]]
	case 25 <= i && i <= 30:
		i -= 25
		return _CartridgeType_name_5[_CartridgeType_index_5[i]:_CartridgeType_index_5[i+1]]
	case 252 <= i && i <= 255:
		i -= 252
		return _CartridgeType_name_6[_CartridgeType_index_6[i]:_CartridgeType_index_6[i+1]]
	default:
		return "CartridgeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
