name: gomeboy

on:
  push:
    branches-ignore:
      - main
  pull_request_review:
    branches:
      - main

jobs:
  test_regressions:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Test
        run: go test -tags test -v tests/*.go -run Test_All
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated test results
          file_pattern: '*.md'
          disable_globbing: true