name: gomeboy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Install libraries
        run: sudo apt-get install libsdl2-dev libgtk-3-dev -y
      - name: Test
        run: go test -v tests/*.go -run Test_All