name: gomeboy

on:
  pull_request_review:
    branches:
      - main

jobs:
  test_regressions:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: install dependencies
        run: go get .
      - name: tests
        run: go test -tags test -v tests/*.go -run Test_Regressions
      - name: import gpg key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: automated test results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: automated test results
          file_pattern: '*.md'
          disable_globbing: true
          commit_options: '-S'